# Generated by Django 4.2.6 on 2023-10-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='matiere',
            new_name='matieres',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='niveau',
            new_name='niveaus',
        ),
    ]
